# Generated by Django 2.0.5 on 2019-10-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(default='', max_length=100)),
                ('p_category', models.CharField(default='', max_length=100)),
                ('p_desc', models.CharField(default='', max_length=300)),
                ('p_price', models.CharField(default='', max_length=100)),
                ('p_upload_date', models.DateField()),
                ('p_capacity', models.CharField(default='', max_length=100)),
                ('p_division', models.CharField(default='', max_length=100)),
                ('p_pan_size', models.CharField(default='', max_length=100)),
                ('p_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
